version: '3'
networks:
    my_network:
        driver: bridge
services:
        web:
            image: nginx:1.22
            container_name: nginx
            restart: always
            ports:
             - "8080:80"
            volumes:
             - "./nginx/conf/conf.d:/etc/nginx/conf.d"
             - "./nginx/logs:/var/log/nginx"
             - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
             - "../app:/home/www/root"
            environment:
                TZ: 'Asia/Shanghai'
                ENV: development
            networks:
             - my_network
            depends_on:
             - php71
             - php72
             - php73
             - php74
             - redis  
        php71:
            image: gamaxtersnow/php71:7.1-fpm-alpine
            container_name: php71
            restart: always
            volumes:
             - "./php/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
             - "./php/var/log:/usr/local/php/var/log"
             - "./php/var/run:/usr/local/php/var/run"
             - "../app:/home/www/root"
            environment:
                TZ: 'Asia/Shanghai'
                ENV: development
            ports:
             - 9000:9000
            networks:
             - my_network
        php72: 
            image: gamaxtersnow/php72:7.2-fpm-alpine
            container_name: php72
            restart: always
            volumes:
             - "./php/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
             - "./php/var/log:/usr/local/php/var/log"
             - "./php/var/run:/usr/local/php/var/run"
             - "../app:/home/www/root"
            environment:
                TZ: 'Asia/Shanghai'
                ENV: development
            networks:
             - my_network
        php73:
            image: gamaxtersnow/php73:7.3-fpm-alpine
            container_name: php73
            restart: always
            volumes:
             - "./php/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
             - "./php/var/log:/usr/local/php/var/log"
             - "./php/var/run:/usr/local/php/var/run"
             - "../app:/home/www/root"
            environment:
                TZ: 'Asia/Shanghai'
                ENV: development
            networks:
             - my_network
        php74:
            image: gamaxtersnow/php74:7.4-fpm-alpine
            container_name: php74
            restart: always
            volumes:
             - "./php/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
             - "./php/var/log:/usr/local/php/var/log"
             - "./php/var/run:/usr/local/php/var/run"
             - "../app:/home/www/root"
             - "./logs/applogs:/home/logs"
            environment:
                TZ: 'Asia/Shanghai'
                ENV: development
            networks:
             - my_network
        redis:
            image: redis:5.0.9
            restart: always
            container_name: redis
            environment:
             TZ: 'Asia/Shanghai'
             ENV: development
            ports:
             - 6379:6379
            networks:
             - my_network
        rabbitmq:
            image: gamaxtersnow/rabbitmq:3.13.2 
            container_name: rabbitmq
            hostname: my-rabbit
            restart: always
            environment:
             TZ: 'Asia/Shanghai'
             RABBITMQ_DEFAULT_USER: admin
             RABBITMQ_DEFAULT_PASS: admin
            ports:
             - 5672:5672
             - 15672:15672
            volumes:
             - "./rabbitmq/mnesia:/var/lib/rabbitmq/mnesia"
            networks:
             - my_network
